server:
  port: 8504
  servlet:
    context-path: /auth/web

spring:
  application:
    name: auth-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  config: classpath:logback.xml
