server:
  port: 8600
  servlet:
    context-path: /basic/web

spring:
  application:
    name: basic-client
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  config: classpath:logback.xml
